In [1]:
import h5py
import numpy as np
import pandas as pd
import wavelets as wl
from scipy import signal
from matplotlib import pyplot as plt

### Figure 2

In [2]:
mydir = '/home/maspe/filer/testFiles/spiking_data/SERT1985/'

In [3]:
chans = ['ch01', 'ch02', 'ch03', 'ch04', 'ch05', 'ch06', 'ch07', 'ch08', 'ch09', 'ch10',
         'ch11', 'ch12', 'ch13', 'ch14', 'ch15', 'ch16', 'ch17', 'ch18', 'ch19', 'ch20',
         'ch21', 'ch22', 'ch23', 'ch24', 'ch25', 'ch26', 'ch27', 'ch28', 'ch29', 'ch30',
         'ch31', 'ch32']

nchannels = len(chans)

In [4]:
fit = []
for chan in chans:
    path = mydir + chan + '/' + chan + '.result.hdf5'
    
    fit.append(h5py.File(path, 'r'))

In [5]:
all_units = []
for a in range(len(fit)):
    for key in fit[a]['spiketimes'].keys():
        all_units.append(fit[a]['spiketimes'][key][()]) # Final "[()]" is to import values from h5py 
        
len(all_units)

53

In [6]:
all_units

[array([      84,      102,      303, ..., 47966704, 47966740, 47966831],
       dtype=uint32),
 array([      83,      304,      450, ..., 47966603, 47966705, 47966740],
       dtype=uint32),
 array([     103,      366,     3124, ..., 47966119, 47966281, 47966432],
       dtype=uint32),
 array([     102,      366,     2086, ..., 47966281, 47966326, 47966387],
       dtype=uint32),
 array([      83,      304,      450, ..., 47966601, 47966737, 47966756],
       dtype=uint32),
 array([      83,      304,      449, ..., 47966536, 47966740, 47966952],
       dtype=uint32),
 array([     103,      365,      770, ..., 47965763, 47966118, 47966281],
       dtype=uint32),
 array([     303,      628,     2115, ..., 47966373, 47966741, 47967002],
       dtype=uint32),
 array([     102,      366,      394, ..., 47966325, 47966790, 47966837],
       dtype=uint32),
 array([    3361,     3818,     4086, ..., 47574946, 47716922, 47717167],
       dtype=uint32),
 array([      84,      102,      303, ..

In [7]:
df = pd.read_excel("/home/maspe/filer/testFiles/spiking_data/SERT1985/entradas_sert1985.xlsx",
                   sheet_name=0, header=None, names=["locs"])
entrances_times = np.array(df['locs'].tolist(), dtype='int')
entrances_times = entrances_times * 30

n_epochs = len(entrances_times)
epochs = []
# epochs_post = []
# post = []
secs = 1.5
sampleRate = 30000
window = int(sampleRate * secs)

# for epoch in range(len(entrances_times)):
#     pre.append(np.arange(entrances_times[epoch] - window, entrances_times[epoch], 1))
#     post.append(np.arange(entrances_times[epoch], entrances_times[epoch] + window, 1))

# for epoch in range(n_epochs):
#     epochs.append([entrances_times[epoch] - window, entrances_times[epoch] + window])
#     epochs_post.append([entrances_times[epoch], entrances_times[epoch] + window])
#     post.append([entrances_times[epoch] + 1, entrances_times[epoch] + window])    

epoch_matrix = []
for epoch in range(20):
    epoch_matrix.append(np.arange(entrances_times[epoch] - window, entrances_times[epoch] + window, 1))
    #post.append(np.arange(entrances_times[epoch], entrances_times[epoch] + window, 1))
    
# epoch_matrix=np.concatenate((np.array(pre), np.array(post)), axis=1)
    
# Flatten vector of all points previous or post to center entrance
# pre_flatten = np.unique([item for sublist in pre for item in sublist])
# post_flatten = np.unique([item for sublist in post for item in sublist])

In [8]:
spikes = []
for unit in range(len(all_units)):
    # np.isin(element, test_elements)
    spikes.append(np.isin(epoch_matrix, all_units[unit]))
    
spikes = np.array(spikes)

In [9]:
spikes.shape

(53, 20, 90000)

In [10]:
units_activity = np.sum(spikes,axis=1)

In [11]:
units_activity.shape

(53, 90000)

In [21]:
mPFC = np.sum(units_activity[0:10,:], axis=0)
NAC = np.sum(units_activity[10:16,:], axis=0)
BLA = np.sum(units_activity[16:25,:], axis=0)
vHip = np.sum(units_activity[25:32,:], axis=0)

In [34]:
vHip.shape

(90000,)

In [42]:
plt.subplot(2,2,1)
plt.plot(np.arange(mPFC.shape[0]), mPFC, '-')
plt.xticks([])
plt.axvline(x=45000, color='black')
plt.title('mPFC')

plt.subplot(2,2,2)
plt.plot(np.arange(NAC.shape[0]), NAC, '-')
plt.xticks([])
plt.axvline(x=45000, color='black')
plt.title('NAC')

plt.subplot(2,2,3)
plt.plot(np.arange(BLA.shape[0]), BLA, '-')
plt.xticks([0, 15000, 30000, 45000, 60000, 75000, 90000], ['-1.5', '-1', '-0.5', '0', '0.5', '1', '1.5'])
plt.axvline(x=45000, color='black')
plt.title('BLA')

plt.subplot(2,2,4)
plt.plot(np.arange(vHip.shape[0]), vHip, '-')
plt.xticks([0, 15000, 30000, 45000, 60000, 75000, 90000], ['-1.5', '-1', '-0.5', '0', '0.5', '1', '1.5'])
plt.axvline(x=45000, color='black')
plt.title('vHip')

plt.savefig(mydir + "spikes.png", dpi=150, facecolor='w', edgecolor='w',
            orientation='portrait', papertype=None, format='png', transparent=False)
    
plt.close()

In [38]:
np.arange(0, 6000, 3000)

array([   0, 3000])

#####################################

#### Backup code

In [ ]:
spikes = []
for unit in range(len(spikes_epochs_pre)):
    # np.isin(element, test_elements)
    spikes.append(np.isin(epoch_matrix, [spikes_epochs_pre[unit] + spikes_epochs_post[unit]]))

In [8]:
spikes_epochs_pre = []
spikes_epochs_post = []
for unit in range(len(all_units)):
    spiketimes_pre = []
    spiketimes_post = []
    for epoch in range(n_epochs):
        spiketimes_pre.extend(all_units[unit][(all_units[unit] > epochs_pre[epoch][0]) & (all_units[unit] < epochs_post[epoch][1])])
        spiketimes_post.extend(all_units[unit][(all_units[unit] > epochs_post[epoch][0]) & (all_units[unit] < epochs_post[epoch][1])])
    spikes_epochs_pre.append(spiketimes_pre)
    spikes_epochs_post.append(spiketimes_post)

In [26]:
len(spikes_epochs_pre[52])

12613

In [63]:
spikes = []
for unit in range(len(spikes_epochs_pre)):
    # np.isin(element, test_elements)
    spikes.append(np.isin(epoch_matrix, [spikes_epochs_pre[unit] + spikes_epochs_post[unit]]))

In [64]:
np.sum(spikes[50], axis=0).shape

(90000,)